name: CONFIGBANK-CI-STAGING

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

permissions:
  contents: write

jobs:
  lint:
    name: Lint Code and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test