name: CONFIGBANK-CI

on:
  push:
    branches:
      - main
    
permissions:
  contents: write

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'
    
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
      
      - name: Build image
        run: docker build -t configbank-img .
      
      - name: Create tag
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          TAG_NAME="build-$TIMESTAMP"
          git tag $TAG_NAME
          git push origin $TAG_NAME